//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psk_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class psk_dbEntities1 : DbContext
    {
        public psk_dbEntities1()
            : base("name=psk_dbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ингредиенты> Ингредиенты { get; set; }
        public virtual DbSet<ОклейкаЭтикетками> ОклейкаЭтикетками { get; set; }
        public virtual DbSet<ПриготовленныеСоусы> ПриготовленныеСоусы { get; set; }
        public virtual DbSet<РецептИнгредиенты> РецептИнгредиенты { get; set; }
        public virtual DbSet<Рецепты> Рецепты { get; set; }
        public virtual DbSet<Соусы> Соусы { get; set; }
        public virtual DbSet<ФасовкаПродукта_> ФасовкаПродукта_ { get; set; }
    }
}
