//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psk_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ингредиенты
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ингредиенты()
        {
            this.РецептИнгредиенты = new HashSet<РецептИнгредиенты>();
        }
    
        public int ИнгредиентId { get; set; }
        public string Название { get; set; }
        public string ЕдиницаИзмерения { get; set; }
        public Nullable<System.DateTime> СрокГодности { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<РецептИнгредиенты> РецептИнгредиенты { get; set; }
    }
}
