//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psk_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Соусы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Соусы()
        {
            this.ОклейкаЭтикетками = new HashSet<ОклейкаЭтикетками>();
            this.ФасовкаПродукта_ = new HashSet<ФасовкаПродукта_>();
        }
    
        public int СоусId { get; set; }
        public string Название { get; set; }
        public Nullable<int> НомерПартии { get; set; }
        public Nullable<System.DateTime> ДатаПроизводства { get; set; }
        public string Ответственный { get; set; }
        public Nullable<int> РецептId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ОклейкаЭтикетками> ОклейкаЭтикетками { get; set; }
        public virtual ПриготовленныеСоусы ПриготовленныеСоусы { get; set; }
        public virtual Рецепты Рецепты { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ФасовкаПродукта_> ФасовкаПродукта_ { get; set; }
    }
}
