//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace psk_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ФасовкаПродукта_
    {
        public int ФасовкаПродуктаId { get; set; }
        public Nullable<int> СоусId { get; set; }
        public string Тара { get; set; }
        public Nullable<int> Количество { get; set; }
        public string Ответственный { get; set; }
    
        public virtual Соусы Соусы { get; set; }
    }
}
